# Generated by Django 3.0.5 on 2020-04-09 16:23

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('courses', '0007_auto_20200409_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
