# Generated by Django 3.0.6 on 2020-05-19 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0016_auto_20200513_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='students_to_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'is_teacher': True}, related_name='teachers_to_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
